# Generated by Django 5.1.4 on 2025-02-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_address_order_city_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
